CyclomaticComplexity:
  Max: 5

AllCops:
  Include:
    - '**/Rakefile'
    - rakelib/*.rake
  Exclude:
    - tmp/**/*
    - files/reveal.js/**/*

Encoding:
  EnforcedStyle: when_needed

FileName:
  Exclude:
    - lib/reveal-ck.rb
